<?php
// Consolidated from production Code Snippet #529.
defined('ABSPATH')||exit;

if(!function_exists('mvm_hub4_health_runtime_compat_v2')){function mvm_hub4_health_runtime_compat_v2(array $data){
 if(empty($data['checks'])||!is_array($data['checks']))return $data;
 $active=array_map('strval',(array)get_option('active_plugins',[]));if(is_multisite())$active=array_merge($active,array_keys((array)get_site_option('active_sitewide_plugins',[])));$peepso=false;foreach($active as $plugin){if(preg_match('~^peepso-core(?:-[^/]+)?/peepso\.php$~i',$plugin)){$peepso=true;break;}}$peepso=$peepso||class_exists('PeepSo')||defined('PEEPSO_VERSION');
 global $wpdb;$table=class_exists('MvM_Hub4_Sources')?MvM_Hub4_Sources::table_name():$wpdb->prefix.'mvm_hub4_sources';$stopped=null;if($table===(string)$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table))){$sql="SELECT COUNT(DISTINCT s.source_post_id) FROM {$table} s INNER JOIN {$wpdb->posts} p ON p.ID=s.source_post_id INNER JOIN {$wpdb->postmeta} pm ON pm.post_id=p.ID WHERE p.post_type='mvm_bron' AND p.post_status='draft' AND pm.meta_key='_mvm_newsradar_source' AND pm.meta_value='1' AND s.status='stopped' AND s.monitor_enabled=0";$stopped=(int)$wpdb->get_var($sql);}
 foreach($data['checks'] as &$check){$id=(string)($check['id']??'');if($id==='plugin_peepso'&&$peepso){$check['status']='ok';$check['summary']='PeepSo is actief.';$check['expected']='actief';$check['actual']='actief';}elseif($id==='newsradar_stopped_duplicates'&&$stopped!==null){$check['status']=$stopped===118?'ok':'critical';$check['summary']=$stopped===118?'De gestopte duplicaatbaseline klopt.':'De gestopte duplicaatbaseline wijkt af.';$check['expected']=118;$check['actual']=$stopped;}}unset($check);
 $summary=['ok'=>0,'warning'=>0,'critical'=>0,'unknown'=>0,'total'=>count($data['checks'])];foreach($data['checks'] as $check){$s=(string)($check['status']??'unknown');if(!isset($summary[$s]))$s='unknown';$summary[$s]++;}$data['summary']=$summary;$data['status']=$summary['critical']>0?'critical':($summary['warning']>0?'warning':'ok');return $data;
}}

add_action('rest_api_init',static function(){if(!class_exists('MvM_Hub4_Health_Check')||!class_exists('MvM_Hub4_Security')||!class_exists('MvM_Hub4_Capabilities'))return;register_rest_route('mvm-hub4/v1','/system/health',['methods'=>WP_REST_Server::READABLE,'permission_callback'=>MvM_Hub4_Security::require_capability(MvM_Hub4_Capabilities::SYSTEM_OVERVIEW),'args'=>['fresh'=>['sanitize_callback'=>'rest_sanitize_boolean','validate_callback'=>'rest_validate_request_arg']],'callback'=>static function(WP_REST_Request $request){$fresh=rest_sanitize_boolean($request->get_param('fresh'));$data=mvm_hub4_health_runtime_compat_v2(MvM_Hub4_Health_Check::run($fresh));if(class_exists('MvM_Hub4_Audit'))MvM_Hub4_Audit::log('system.health_view','success',['object_type'=>'system_health','context'=>['fresh'=>(bool)$fresh,'status'=>sanitize_key((string)($data['status']??'unknown')),'critical'=>(int)($data['summary']['critical']??0),'warning'=>(int)($data['summary']['warning']??0)]]);return rest_ensure_response($data);}],true);},200);