<?php
// Consolidated from production Code Snippet #501.
defined( 'ABSPATH' ) || exit;

if ( ! function_exists( 'mvm_hub_source_admin_url_v1' ) ) {
function mvm_hub_source_admin_url_v1( $post ) {
    if ( ! $post instanceof WP_Post ) return '';
    if ( class_exists('MvM_Hub4_Source_Repository') && method_exists('MvM_Hub4_Source_Repository','extract_external_url') ) return MvM_Hub4_Source_Repository::extract_external_url((string)$post->post_content);
    $text=html_entity_decode(wp_strip_all_tags((string)$post->post_content),ENT_QUOTES,get_bloginfo('charset'));
    return preg_match('/https?:\/\/[^\s<>"\']+/iu',$text,$m)?esc_url_raw(rtrim($m[0],'.,);]')):'';
}}
if ( ! function_exists( 'mvm_hub_source_admin_content_v1' ) ) {
function mvm_hub_source_admin_content_v1( $content,$url ) {
    $content=(string)$content;$url=esc_url_raw((string)$url);if(''===$url)return $content;$row='<p><strong>URL:</strong> '.esc_html($url).'</p>';
    if(preg_match('~<p[^>]*>\s*<strong>\s*URL\s*:\s*</strong>.*?</p>~is',$content))return preg_replace('~<p[^>]*>\s*<strong>\s*URL\s*:\s*</strong>.*?</p>~is',$row,$content,1);
    return rtrim($content).$row;
}}
if ( ! function_exists( 'mvm_hub_source_admin_legacy_v1' ) ) {
function mvm_hub_source_admin_legacy_v1( $post_id,array $data,$create=false ) {
    $sources=get_option('mvm_bh_sources',[]);if(!is_array($sources))$sources=[];$legacy_id=absint(get_post_meta($post_id,'_mvm_newsradar_legacy_source_id',true));
    if(!$legacy_id&&$create){$max=0;foreach($sources as $s)if(is_array($s))$max=max($max,absint($s['id']??0));$legacy_id=$max+1;update_post_meta($post_id,'_mvm_newsradar_legacy_source_id',$legacy_id);}
    if(!$legacy_id)return 0;$active=!empty($data['monitor'])&&'active'===$data['status'];$found=false;
    foreach($sources as $i=>$source){if(!is_array($source)||absint($source['id']??0)!==$legacy_id)continue;$source['name']=$data['title'];$source['url']=$data['url'];$source['category']=$data['category_label'];$source['frequency']=$data['frequency_label'];$source['active']=$active;$source['excluded']=!$active;$sources[$i]=$source;$found=true;break;}
    if(!$found&&$create)$sources[]=['id'=>$legacy_id,'priority'=>'B','name'=>$data['title'],'usage'=>'Hub bronbeheer','category'=>$data['category_label'],'frequency'=>$data['frequency_label'],'url'=>$data['url'],'social'=>'','active'=>$active,'excluded'=>!$active,'last_checked'=>'','next_check'=>'','web_checked'=>'','note'=>'Aangemaakt via Hub Bronnencontrole'];
    update_option('mvm_bh_sources',array_values($sources),false);update_post_meta($post_id,'_mvm_newsradar_source',1);update_post_meta($post_id,'_mvm_newsradar_active',$active?1:0);update_post_meta($post_id,'_mvm_newsradar_excluded',$active?0:1);return $legacy_id;
}}
if ( ! function_exists( 'mvm_hub_source_admin_payload_v1' ) ) {
function mvm_hub_source_admin_payload_v1( WP_REST_Request $request ) {
    $p=(array)$request->get_json_params();$title=sanitize_text_field((string)($p['title']??''));$url=esc_url_raw((string)($p['url']??''));
    if(''===$title)return new WP_Error('mvm_source_title_required','Bronnaam is verplicht.',['status'=>400]);if(''===$url||!wp_http_validate_url($url))return new WP_Error('mvm_source_url_required','Vul een geldige http(s)-bron-URL in.',['status'=>400]);
    $category=class_exists('MvM_Hub4_Sources')?MvM_Hub4_Sources::sanitize_category((string)($p['category']??'overig')):sanitize_key((string)($p['category']??'overig'));$frequency=class_exists('MvM_Hub4_Sources')?MvM_Hub4_Sources::sanitize_frequency((string)($p['frequency']??'weekly')):sanitize_key((string)($p['frequency']??'weekly'));$status=class_exists('MvM_Hub4_Sources')?MvM_Hub4_Sources::sanitize_status((string)($p['status']??'active')):sanitize_key((string)($p['status']??'active'));
    $cats=class_exists('MvM_Hub4_Sources')?MvM_Hub4_Sources::categories():[$category=>$category];$freqs=class_exists('MvM_Hub4_Sources')?MvM_Hub4_Sources::frequencies():[$frequency=>['label'=>$frequency]];
    return ['title'=>$title,'url'=>$url,'category'=>$category,'frequency'=>$frequency,'status'=>$status,'monitor'=>array_key_exists('monitorEnabled',$p)?rest_sanitize_boolean($p['monitorEnabled']):true,'private_note'=>sanitize_textarea_field((string)($p['privateNote']??'')),'category_label'=>(string)($cats[$category]??$category),'frequency_label'=>(string)($freqs[$frequency]['label']??$frequency)];
}}
add_action('rest_api_init',static function(){
    if(!class_exists('MvM_Hub4_Security')||!class_exists('MvM_Hub4_Capabilities'))return;$manage=MvM_Hub4_Security::require_capability(MvM_Hub4_Capabilities::SOURCE_MANAGE);
    register_rest_route('mvm-hub4/v1','/source-admin',['methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>$manage,'callback'=>static function(WP_REST_Request $request){$data=mvm_hub_source_admin_payload_v1($request);if(is_wp_error($data))return $data;$content='<p><strong>Bron.</strong> Aangemaakt via Hub Bronnencontrole.</p><p><strong>URL:</strong> '.esc_html($data['url']).'</p>';$id=wp_insert_post(['post_type'=>'mvm_bron','post_status'=>'publish','post_title'=>$data['title'],'post_content'=>$content],true);if(is_wp_error($id))return $id;$id=absint($id);update_post_meta($id,'_yoast_wpseo_meta-robots-noindex',1);if(class_exists('MvM_Hub4_Sources')){$saved=MvM_Hub4_Sources::save_state($id,['monitor_enabled'=>$data['monitor'],'category'=>$data['category'],'frequency'=>$data['frequency'],'status'=>$data['status'],'private_note'=>$data['private_note']]);if(is_wp_error($saved)){wp_update_post(['ID'=>$id,'post_status'=>'draft']);return $saved;}}$legacy=mvm_hub_source_admin_legacy_v1($id,$data,true);if(class_exists('MvM_Hub4_Audit'))MvM_Hub4_Audit::log('source.created','success',['object_type'=>'source','object_id'=>$id,'context'=>['legacy_id'=>$legacy]]);return rest_ensure_response(['ok'=>true,'id'=>$id,'legacyId'=>$legacy]);}]);
    register_rest_route('mvm-hub4/v1','/source-admin/(?P<id>\d+)',[
      ['methods'=>WP_REST_Server::READABLE,'permission_callback'=>$manage,'callback'=>static function(WP_REST_Request $request){$id=absint($request['id']);$post=get_post($id);if(!$post instanceof WP_Post||'mvm_bron'!==$post->post_type)return new WP_Error('mvm_source_missing','Bron niet gevonden.',['status'=>404]);$state=class_exists('MvM_Hub4_Sources')?MvM_Hub4_Sources::get_state($id):null;return rest_ensure_response(['id'=>$id,'title'=>html_entity_decode(wp_strip_all_tags($post->post_title),ENT_QUOTES,get_bloginfo('charset')),'url'=>mvm_hub_source_admin_url_v1($post),'category'=>$state['category']??'overig','frequency'=>$state['frequency']??'weekly','status'=>$state['status']??'active','monitorEnabled'=>!empty($state['monitor_enabled']),'privateNote'=>(string)($state['private_note']??''),'legacyId'=>absint(get_post_meta($id,'_mvm_newsradar_legacy_source_id',true))]);}],
      ['methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>$manage,'callback'=>static function(WP_REST_Request $request){$id=absint($request['id']);$post=get_post($id);if(!$post instanceof WP_Post||'mvm_bron'!==$post->post_type||'publish'!==$post->post_status)return new WP_Error('mvm_source_missing','Bron niet gevonden of niet actief.',['status'=>404]);$data=mvm_hub_source_admin_payload_v1($request);if(is_wp_error($data))return $data;$updated=wp_update_post(['ID'=>$id,'post_title'=>$data['title'],'post_content'=>mvm_hub_source_admin_content_v1($post->post_content,$data['url'])],true);if(is_wp_error($updated))return $updated;if(class_exists('MvM_Hub4_Sources')){$saved=MvM_Hub4_Sources::save_state($id,['monitor_enabled'=>$data['monitor'],'category'=>$data['category'],'frequency'=>$data['frequency'],'status'=>$data['status'],'private_note'=>$data['private_note']]);if(is_wp_error($saved))return $saved;}$legacy=mvm_hub_source_admin_legacy_v1($id,$data,false);if(class_exists('MvM_Hub4_Audit'))MvM_Hub4_Audit::log('source.full_update','success',['object_type'=>'source','object_id'=>$id]);return rest_ensure_response(['ok'=>true,'id'=>$id,'legacyId'=>$legacy]);}]
    ]);
    register_rest_route('mvm-hub4/v1','/source-admin/(?P<id>\d+)/archive',['methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>$manage,'callback'=>static function(WP_REST_Request $request){$id=absint($request['id']);$post=get_post($id);if(!$post instanceof WP_Post||'mvm_bron'!==$post->post_type||'publish'!==$post->post_status)return new WP_Error('mvm_source_missing','Bron niet gevonden of al gearchiveerd.',['status'=>404]);$state=class_exists('MvM_Hub4_Sources')?MvM_Hub4_Sources::get_state($id):null;$archive=get_option('mvm_hub_source_archive_v1',[]);if(!is_array($archive))$archive=[];$archive[$id]=['archived_at'=>gmdate('c'),'archived_by'=>get_current_user_id(),'post'=>['title'=>$post->post_title,'content'=>$post->post_content],'state'=>$state,'legacy_id'=>absint(get_post_meta($id,'_mvm_newsradar_legacy_source_id',true))];update_option('mvm_hub_source_archive_v1',$archive,false);if(class_exists('MvM_Hub4_Sources'))MvM_Hub4_Sources::save_state($id,['monitor_enabled'=>false,'status'=>'stopped']);$legacy_id=absint(get_post_meta($id,'_mvm_newsradar_legacy_source_id',true));if($legacy_id){$sources=get_option('mvm_bh_sources',[]);if(is_array($sources)){foreach($sources as $i=>$s){if(is_array($s)&&absint($s['id']??0)===$legacy_id){$sources[$i]['active']=false;$sources[$i]['excluded']=true;break;}}update_option('mvm_bh_sources',array_values($sources),false);}}update_post_meta($id,'_mvm_newsradar_active',0);update_post_meta($id,'_mvm_newsradar_excluded',1);update_post_meta($id,'_mvm_hub_archived_at',gmdate('c'));$done=wp_update_post(['ID'=>$id,'post_status'=>'draft'],true);if(is_wp_error($done))return $done;if(class_exists('MvM_Hub4_Audit'))MvM_Hub4_Audit::log('source.archived','success',['object_type'=>'source','object_id'=>$id]);return rest_ensure_response(['ok'=>true,'id'=>$id]);}]);
});