<?php
// Consolidated from production Code Snippet #525.
defined('ABSPATH') || exit;

if(!function_exists('mvm_newsradar_agenda_analyze_v1')){function mvm_newsradar_agenda_analyze_v1(array $pending,array $all_rows){
 if(!class_exists('WordPress\\AiClient\\AiClient'))return new WP_Error('mvm_agenda_ai_client','WordPress AI Client ontbreekt.');
 $payload=[];foreach($pending as $r){$ts=(int)($r['agenda_start_ts']??0);$payload[]=[
  'id'=>(string)($r['id']??''),'source'=>(string)($r['source']??''),'source_url'=>(string)($r['source_url']??''),'title'=>(string)($r['title']??''),'url'=>(string)($r['url']??''),
  'is_agenda_item'=>true,'agenda_date'=>(string)($r['agenda_date']??''),'agenda_start_iso'=>$ts?wp_date(DATE_ATOM,$ts):'','agenda_excerpt'=>function_exists('mvm_newsradar_text_sub_v1')?mvm_newsradar_text_sub_v1((string)($r['excerpt']??''),0,2500):(string)($r['excerpt']??''),
  'published'=>(string)($r['published']??''),'date_issues'=>(array)($r['date_issues']??[]),'local_score'=>(int)($r['local_score']??0),'recent_related'=>function_exists('mvm_newsradar_recent_context_v1')?mvm_newsradar_recent_context_v1($all_rows,(string)($r['id']??'')):[]
 ];}
 $today=wp_date('l d-m-Y');$instruction="Je bent de nieuwsselectie van Mierlo voor Mierlo. Vandaag is {$today}, tijdzone Europe/Amsterdam. Deze items komen uit expliciete agenda-/kalenderpagina's. agenda_date en agenda_start_iso zijn door de crawler uit de bronagenda vastgesteld en zijn leidend voor de evenementdatum; beweer dus niet dat maand, jaar of exacte datum ontbreekt als deze velden gevuld zijn. Een ontbrekende publicatiedatum van de agenda-pagina maakt een duidelijke toekomstige evenementdatum niet automatisch onzeker. Beoordeel wel lokale relevantie, concreetheid en betrouwbaarheid. Mierlo betekent het dorp Mierlo in Noord-Brabant. Markeer publiceerbaar wanneer het evenement concreet, toekomstig, lokaal relevant en voldoende duidelijk is; controleren bij echte inhoudelijke onzekerheid; niet_mierlo wanneer het niet relevant is. confidence moet ALTIJD een geheel getal van 0 tot en met 100 zijn, waarbij 100 maximale zekerheid is. Verzin geen feiten. Geef een korte Nederlandse samenvatting.";
 $shape=['items'=>[['id'=>'exact aangeleverd id','status'=>'publiceerbaar|controleren|niet_mierlo|dubbel','category'=>'Evenementen / Agenda','summary'=>'korte Nederlandse samenvatting','confidence'=>80,'reason'=>'korte reden','change_relevant'=>false,'change_summary'=>'','relationship_type'=>'geen|eerder_bericht|vervolg|gerelateerd']]];
 $prompt=$instruction."\n\nGeef uitsluitend geldige JSON zonder markdown. Geef per item exact één resultaat. Structuur:\n".wp_json_encode($shape,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n\nItems:\n".wp_json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
 $models=['gemini-3.6-flash','gemini-3.5-flash-lite','gemini-3.1-flash-lite'];$text='';$used='';$errors=[];foreach($models as $model){try{$res=\WordPress\AiClient\AiClient::prompt($prompt)->usingModelPreference(['google',$model])->generateTextResult();$candidate=method_exists($res,'toText')?trim((string)$res->toText()):'';if($candidate!==''){$text=$candidate;$used=$model;break;}$errors[]=$model.': leeg';}catch(Throwable $e){$errors[]=$model.': '.sanitize_text_field($e->getMessage());}}
 if($text==='')return new WP_Error('mvm_agenda_ai_request',substr(implode(' | ',$errors),0,500));update_option('mvm_newsradar_gemini_last_model_v1',$used,false);$text=preg_replace('/^```(?:json)?\s*/i','',$text);$text=preg_replace('/\s*```$/','',$text);$f=strpos($text,'{');$l=strrpos($text,'}');if(false!==$f&&false!==$l&&$l>=$f)$text=substr($text,$f,$l-$f+1);$json=json_decode($text,true);if(!is_array($json)||empty($json['items'])||!is_array($json['items']))return new WP_Error('mvm_agenda_ai_parse','Gemini gaf geen geldige agenda-JSON terug.');
 $allowed=array_fill_keys(array_map(static fn($r)=>(string)($r['id']??''),$pending),true);$clean=[];foreach($json['items'] as $i){if(!is_array($i))continue;$id=(string)($i['id']??'');if($id===''||!isset($allowed[$id]))continue;$status=sanitize_key((string)($i['status']??'controleren'));if(!in_array($status,['publiceerbaar','controleren','niet_mierlo','dubbel'],true))$status='controleren';$rel=sanitize_key((string)($i['relationship_type']??'geen'));if(!in_array($rel,['geen','eerder_bericht','vervolg','gerelateerd'],true))$rel='geen';$cv=$i['confidence']??0;$cv=is_numeric($cv)?(float)$cv:0;if($cv>0&&$cv<=1)$cv*=100;$cv=max(0,min(100,(int)round($cv)));$clean[]=['id'=>$id,'status'=>$status,'category'=>'Evenementen / Agenda','summary'=>sanitize_textarea_field((string)($i['summary']??'')),'confidence'=>$cv,'reason'=>sanitize_textarea_field((string)($i['reason']??'')),'change_relevant'=>!empty($i['change_relevant']),'change_summary'=>sanitize_textarea_field((string)($i['change_summary']??'')),'relationship_type'=>$rel];}
 return $clean?:new WP_Error('mvm_agenda_ai_empty','Geen bruikbare agenda-beoordelingen terug.');
}}

if(!function_exists('mvm_newsradar_agenda_apply_v1')){function mvm_newsradar_agenda_apply_v1(array $analysis){
 if(!function_exists('mvm_newsradar_apply_gemini_v1'))return 0;$processed=mvm_newsradar_apply_gemini_v1($analysis);if(!$processed)return 0;$wanted=[];foreach($analysis as $a)if(($a['status']??'')==='publiceerbaar'&&!empty($a['id']))$wanted[(string)$a['id']]=$a;if(!$wanted)return $processed;$rows=get_option('mvm_bh_news_radar_results',[]);$changed=false;$today=strtotime(wp_date('Y-m-d').' 00:00:00');foreach(is_array($rows)?$rows:[] as &$r){$id=(string)($r['id']??'');if(!isset($wanted[$id])||empty($r['agenda_date']))continue;$ats=(int)($r['agenda_start_ts']??0);if($ats<$today)continue;$a=$wanted[$id];$r['status']='publiceerbaar';$r['reason']=trim((string)($a['reason']??'').' Evenementdatum '.$r['agenda_date'].' is vastgesteld via de bronagenda; een ontbrekende publicatiedatum van de agenda-pagina blokkeert deze evenementdatum niet.');$changed=true;}unset($r);if($changed)update_option('mvm_bh_news_radar_results',$rows,false);return $processed;
}}

if(!function_exists('mvm_newsradar_agenda_ai_hook_v1')){function mvm_newsradar_agenda_ai_hook_v1($cycle=''){
 if(!function_exists('mvm_newsradar_should_google_fallback_v1')||!mvm_newsradar_should_google_fallback_v1())return;$rows=get_option('mvm_bh_news_radar_results',[]);$pending=[];foreach(is_array($rows)?$rows:[] as $r){if(is_array($r)&&!empty($r['ai_pending'])&&empty($r['dismissed'])&&!empty($r['agenda_date'])&&!empty($r['agenda_start_ts'])){$pending[]=$r;if(count($pending)>=2)break;}}if(!$pending)return;
 remove_action('mvm_bh_news_radar_ai_batch','mvm_newsradar_google_fallback_hook_v5',5);if(function_exists('mvm_newsradar_remove_legacy_ai_once_v1'))mvm_newsradar_remove_legacy_ai_once_v1();$analysis=mvm_newsradar_agenda_analyze_v1($pending,$rows);if(is_wp_error($analysis)){update_option('mvm_newsradar_gemini_fallback_status_v1',['ok'=>false,'time'=>wp_date(DATE_ATOM),'message'=>sanitize_text_field($analysis->get_error_message()),'batch'=>2,'agenda_context'=>true],false);if(function_exists('mvm_newsradar_schedule_ai_retry_v3'))mvm_newsradar_schedule_ai_retry_v3($cycle,60);return;}
 $n=mvm_newsradar_agenda_apply_v1($analysis);$after=get_option('mvm_bh_news_radar_results',[]);$remaining=0;foreach(is_array($after)?$after:[] as $r)if(is_array($r)&&!empty($r['ai_pending'])&&empty($r['dismissed']))$remaining++;$model=(string)get_option('mvm_newsradar_gemini_last_model_v1','');update_option('mvm_newsradar_gemini_fallback_status_v1',['ok'=>true,'time'=>wp_date(DATE_ATOM),'processed'=>$n,'remaining'=>$remaining,'model'=>$model,'batch'=>2,'agenda_context'=>true],false);if(function_exists('mvm_newsradar_schedule_ai_retry_v3'))mvm_newsradar_schedule_ai_retry_v3($cycle,$remaining?20:5);
}}
add_action('init',static function(){add_action('mvm_bh_news_radar_ai_batch','mvm_newsradar_agenda_ai_hook_v1',4,1);},30);