<?php
// Consolidated from production Code Snippet #521.
defined( 'ABSPATH' ) || exit;
if(!function_exists('mvm_newsradar_schedule_ai_retry_v3')){function mvm_newsradar_schedule_ai_retry_v3($cycle,$delay=60){$cycle=(string)$cycle;if($cycle==='')return;$args=[$cycle];if(!wp_next_scheduled('mvm_bh_news_radar_ai_batch',$args))wp_schedule_single_event(time()+max(5,(int)$delay),'mvm_bh_news_radar_ai_batch',$args);}}
if(!function_exists('mvm_newsradar_google_fallback_hook_v5')){function mvm_newsradar_google_fallback_hook_v5($cycle=''){
 if(!function_exists('mvm_newsradar_should_google_fallback_v1')||!mvm_newsradar_should_google_fallback_v1())return;if(!function_exists('mvm_newsradar_gemini_analyze_v1')||!function_exists('mvm_newsradar_apply_gemini_v1'))return;
 $rows=get_option('mvm_bh_news_radar_results',[]);if(!is_array($rows))return;$excluded=[];$sources=get_option('mvm_bh_sources',[]);foreach(is_array($sources)?$sources:[] as $s)if(is_array($s)&&!empty($s['excluded'])&&!empty($s['id']))$excluded[(int)$s['id']]=true;$changed=false;
 foreach($rows as &$r){if(!is_array($r)||empty($r['ai_pending']))continue;$sid=(int)($r['source_id']??0);if($sid&&isset($excluded[$sid])){$r['ai_pending']=0;$r['email_pending']=0;$r['status']='controleren';$r['reason']='Bron is uitgesloten van de Nieuwsradar; deze kandidaat is niet naar AI gestuurd.';$changed=true;continue;}if(class_exists('MvM_Hub4_Newsradar_Local_Scope')){$scope=MvM_Hub4_Newsradar_Local_Scope::assess($r);$r['mvm_scope_score']=(int)($scope['score']??0);$r['mvm_scope_decision']=(string)($scope['decision']??'review');if(($scope['decision']??'')==='reject'){$r['ai_pending']=0;$r['email_pending']=0;$r['status']='niet_mierlo';$r['reason']='Mierlo-scopefilter: '.implode(' ',(array)($scope['reasons']??[]));$changed=true;}}}unset($r);if($changed)update_option('mvm_bh_news_radar_results',$rows,false);
 $pending=[];foreach($rows as $r){if(!is_array($r)||empty($r['ai_pending'])||!empty($r['dismissed']))continue;$pending[]=$r;if(count($pending)>=2)break;}if(!$pending)return;
 if(function_exists('mvm_newsradar_remove_legacy_ai_once_v1'))mvm_newsradar_remove_legacy_ai_once_v1();
 $analysis=mvm_newsradar_gemini_analyze_v1($pending,$rows);if(is_wp_error($analysis)){$message=sanitize_text_field($analysis->get_error_message());update_option('mvm_newsradar_gemini_fallback_status_v1',['ok'=>false,'time'=>wp_date(DATE_ATOM),'message'=>$message,'batch'=>2,'retry_seconds'=>60],false);$state=get_option('mvm_bh_news_radar_state',[]);if(is_array($state)&&($cycle===''||(string)($state['cycle']??'')===(string)$cycle)){$state['running']=1;$state['phase']='ai';$state['last_message']='Gemini tijdelijk niet beschikbaar; automatische retry over circa 60 seconden. '.substr($message,0,180);update_option('mvm_bh_news_radar_state',$state,false);}mvm_newsradar_schedule_ai_retry_v3($cycle,60);return;}
 $processed=mvm_newsradar_apply_gemini_v1($analysis);if($processed<1){update_option('mvm_newsradar_gemini_fallback_status_v1',['ok'=>false,'time'=>wp_date(DATE_ATOM),'message'=>'Gemini gaf geen toepasbare Radar-beoordeling terug.','batch'=>2,'retry_seconds'=>60],false);mvm_newsradar_schedule_ai_retry_v3($cycle,60);return;}
 $model=(string)get_option('mvm_newsradar_gemini_last_model_v1','gemini-3.7-flash');$rows_after=get_option('mvm_bh_news_radar_results',[]);$remaining=0;foreach(is_array($rows_after)?$rows_after:[] as $r)if(is_array($r)&&!empty($r['ai_pending'])&&empty($r['dismissed']))$remaining++;$state=get_option('mvm_bh_news_radar_state',[]);if(is_array($state)&&($cycle===''||(string)($state['cycle']??'')===(string)$cycle)){$state['running']=$remaining?1:0;$state['phase']=$remaining?'ai':'done';$state['ai_processed']=(int)($state['ai_processed']??0)+$processed;$state['last_message']=$processed.' kandidaten door '.$model.' beoordeeld (automatische providerfallback, batch 2; 20s cadans).'.($remaining?' '.$remaining.' wachten nog op AI.':' AI-wachtrij leeg; cyclus afgerond.');update_option('mvm_bh_news_radar_state',$state,false);}update_option('mvm_newsradar_gemini_fallback_status_v1',['ok'=>true,'time'=>wp_date(DATE_ATOM),'processed'=>$processed,'remaining'=>$remaining,'model'=>$model,'batch'=>2,'cadence_seconds'=>20],false);if($remaining)mvm_newsradar_schedule_ai_retry_v3($cycle,20);
}}
add_action('init',static function(){remove_action('mvm_bh_news_radar_ai_batch','mvm_newsradar_google_fallback_hook_v1',5);remove_action('mvm_bh_news_radar_ai_batch','mvm_newsradar_google_fallback_hook_v2',5);remove_action('mvm_bh_news_radar_ai_batch','mvm_newsradar_google_fallback_hook_v3',5);remove_action('mvm_bh_news_radar_ai_batch','mvm_newsradar_google_fallback_hook_v4',5);add_action('mvm_bh_news_radar_ai_batch','mvm_newsradar_google_fallback_hook_v5',5,1);$state=get_option('mvm_bh_news_radar_state',[]);if(!is_array($state)||empty($state['cycle']))return;$should_resume=!empty($state['running'])&&(string)($state['phase']??'')==='ai';if(!$should_resume&&function_exists('mvm_newsradar_should_google_fallback_v1')&&mvm_newsradar_should_google_fallback_v1()){$rows=get_option('mvm_bh_news_radar_results',[]);foreach(is_array($rows)?$rows:[] as $r){if(is_array($r)&&!empty($r['ai_pending'])&&empty($r['dismissed'])){$should_resume=true;break;}}if($should_resume){$state['running']=1;$state['phase']='ai';$state['last_message']='Automatische AI-fallback hervat de vastgelopen Nieuwsradar-cyclus.';update_option('mvm_bh_news_radar_state',$state,false);}}if($should_resume)mvm_newsradar_schedule_ai_retry_v3((string)$state['cycle'],5);},20);