<?php
// Consolidated from production Code Snippet #502.
defined( 'ABSPATH' ) || exit;
add_action('template_redirect',static function(){
    if(is_admin()||wp_doing_ajax())return;$path=trim((string)wp_parse_url(isset($_SERVER['REQUEST_URI'])?wp_unslash($_SERVER['REQUEST_URI']):'',PHP_URL_PATH),'/');if(!preg_match('#^hub4?(?:/|$)#',$path))return;
    ob_start(static function($html){
        if(false===strpos($html,'class="mvm-hub4"')&&false===strpos($html,"class='mvm-hub4'"))return $html;if(false!==strpos($html,'id="mvm-hub-source-admin-ui-v1"'))return $html;
        $asset=<<<'MVMUI'
<script id="mvm-hub-source-admin-ui-v1">
(()=>{'use strict';const cfg=window.MvMHub4Config||{};if(!cfg.restRoot||!cfg.restNonce)return;let cache=[],opts=null;const nativeFetch=window.fetch.bind(window);
window.fetch=async(input,init)=>{const res=await nativeFetch(input,init);try{const u=new URL(input instanceof Request?input.url:String(input),location.href);if(u.pathname.includes('/mvm-hub4/v1/sources')&&(!init||!init.method||String(init.method).toUpperCase()==='GET')){const j=await res.clone().json();if(u.pathname.endsWith('/sources/options'))opts=j;else if(Array.isArray(j.items))cache=j.items;}}catch(e){}return res;};
const api=async(path,options={})=>{const r=await nativeFetch(new URL(String(path).replace(/^\//,''),cfg.restRoot).toString(),{...options,credentials:'same-origin',cache:'no-store',headers:{'X-WP-Nonce':cfg.restNonce,'Content-Type':'application/json','Accept':'application/json',...(options.headers||{})}});let j={};try{j=await r.json();}catch(e){}if(!r.ok)throw new Error(j.message||'Actie mislukt.');return j;};
const el=(tag,attrs={},text='')=>{const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>{if(k==='class')n.className=v;else n.setAttribute(k,String(v));});if(text)n.textContent=text;return n;};
const refresh=()=>{const q=document.querySelector('#mvm-source-search');if(q){q.dispatchEvent(new Event('input',{bubbles:true}));}else location.reload();};
const openModal=async(id=0)=>{let data={title:'',url:'',category:'overig',frequency:'weekly',status:'active',monitorEnabled:true,privateNote:''};try{if(id)data=await api(`source-admin/${id}`);}catch(err){alert(err.message);return;}const ov=el('div',{class:'mvm-source-admin-modal'}),card=el('section',{class:'mvm-source-admin-card',role:'dialog','aria-modal':'true','aria-labelledby':'mvm-source-admin-title'});card.appendChild(el('h2',{id:'mvm-source-admin-title'},id?'Bron wijzigen':'Bron toevoegen'));const form=el('form');
const field=(label,name,type='text')=>{const l=el('label');l.append(document.createTextNode(label));const i=type==='textarea'?el('textarea',{name,rows:'3'}):el('input',{name,type});i.value=data[name]??'';l.appendChild(i);form.appendChild(l);return i;};field('Naam','title');field('Website / bron-URL','url','url');
const select=(label,name,choices)=>{const l=el('label');l.append(document.createTextNode(label));const s=el('select',{name});(choices||[]).forEach(c=>{const o=el('option',{value:c.value},c.label);if(String(data[name])===String(c.value))o.selected=true;s.appendChild(o);});l.appendChild(s);form.appendChild(l);};select('Categorie','category',opts?.categories||[{value:'overig',label:'Overig'}]);select('Frequentie','frequency',opts?.frequencies||[{value:'weekly',label:'Wekelijks'}]);select('Status','status',opts?.statuses||[{value:'active',label:'Actief'}]);
const check=el('label',{class:'mvm-source-admin-check'}),cb=el('input',{type:'checkbox',name:'monitorEnabled'});cb.checked=Boolean(data.monitorEnabled);check.appendChild(cb);check.append(document.createTextNode(' Automatische controle inschakelen'));form.appendChild(check);field('Interne notitie','privateNote','textarea');
const actions=el('div',{class:'mvm-source-admin-actions'}),save=el('button',{type:'submit',class:'mvm-hub4__button'},id?'Wijzigingen opslaan':'Bron toevoegen'),close=el('button',{type:'button',class:'mvm-source-admin-secondary'},'Annuleren');actions.append(save,close);form.appendChild(actions);card.appendChild(form);ov.appendChild(card);document.body.appendChild(ov);close.onclick=()=>ov.remove();ov.addEventListener('click',e=>{if(e.target===ov)ov.remove();});
form.onsubmit=async e=>{e.preventDefault();save.disabled=true;const payload=Object.fromEntries(new FormData(form).entries());payload.monitorEnabled=cb.checked;try{await api(id?`source-admin/${id}`:'source-admin',{method:'POST',body:JSON.stringify(payload)});ov.remove();refresh();}catch(err){alert(err.message);save.disabled=false;}};};
const decorate=()=>{const section=[...document.querySelectorAll('.mvm-hub4__section')].find(s=>s.querySelector('h2')?.textContent.includes('Handmatige bronnencontrole'));if(!section)return;const canManage=Boolean(opts?.permissions?.canManage);const head=section.querySelector('.mvm-hub4__section-head');if(head&&canManage&&!head.querySelector('[data-mvm-source-add]')){const add=el('button',{type:'button','data-mvm-source-add':'1',class:'mvm-hub4__button'},'Bron toevoegen');add.onclick=()=>openModal(0);head.appendChild(add);}
const rows=section.querySelectorAll('[data-source-results] tbody tr');rows.forEach((row,i)=>{const item=cache[i];if(!item||row.dataset.mvmSourceAdmin)return;row.dataset.mvmSourceAdmin=String(item.id);if(!canManage)return;const td=row.lastElementChild;if(!td)return;const edit=el('button',{type:'button',class:'mvm-source-admin-mini'},'Bewerken');edit.onclick=()=>openModal(item.id);const remove=el('button',{type:'button',class:'mvm-source-admin-mini mvm-source-admin-danger'},'Verwijderen');remove.onclick=async()=>{if(!confirm('Deze bron verwijderen uit Bronnencontrole? De bron wordt veilig gearchiveerd; monitoring en AI worden uitgeschakeld.'))return;remove.disabled=true;try{await api(`source-admin/${item.id}/archive`,{method:'POST',body:'{}'});refresh();}catch(err){alert(err.message);remove.disabled=false;}};td.append(edit,remove);});};
new MutationObserver(decorate).observe(document.documentElement,{childList:true,subtree:true});window.setInterval(decorate,700);})();
</script>
<style id="mvm-hub-source-admin-ui-v1-css">.mvm-source-admin-modal{position:fixed;inset:0;z-index:999999;display:grid;place-items:center;padding:20px;background:rgba(15,23,42,.7)}.mvm-source-admin-card{width:min(620px,100%);max-height:calc(100vh - 40px);overflow:auto;padding:22px;border:1px solid var(--mvm-hub4-border,#c5d3df);border-radius:14px;background:var(--mvm-hub4-surface,#fff);color:var(--mvm-hub4-text,#17222d);box-shadow:0 24px 70px rgba(0,0,0,.3)}.mvm-source-admin-card h2{margin:0 0 14px}.mvm-source-admin-card label{display:grid;gap:5px;margin:11px 0;font-weight:750}.mvm-source-admin-card input,.mvm-source-admin-card select,.mvm-source-admin-card textarea{box-sizing:border-box;width:100%;min-height:42px;padding:8px 10px;border:1px solid var(--mvm-hub4-border,#8299ad);border-radius:8px;background:var(--mvm-hub4-surface,#fff);color:var(--mvm-hub4-text,#17222d)}.mvm-source-admin-check{display:flex!important;align-items:center;gap:8px!important}.mvm-source-admin-check input{width:auto!important;min-height:auto!important}.mvm-source-admin-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:18px}.mvm-source-admin-actions button,.mvm-source-admin-mini{min-height:36px;padding:7px 10px;border:1px solid #1966AE;border-radius:8px;background:#1966AE;color:#fff!important;font-weight:800;cursor:pointer}.mvm-source-admin-secondary{background:#fff!important;color:#1966AE!important}.mvm-source-admin-mini{margin:2px;min-height:30px;padding:4px 7px;font-size:.8rem}.mvm-source-admin-danger{border-color:#a61b1b!important;background:#a61b1b!important}@media(max-width:600px){.mvm-source-admin-actions{display:grid}.mvm-source-admin-actions>*{width:100%}}</style>
MVMUI;
        $pos=stripos($html,'</head>');return false!==$pos?substr_replace($html,$asset.'</head>',$pos,7):$asset.$html;
    });
},-850);