<?php
// Consolidated from production Code Snippet #504.
defined( 'ABSPATH' ) || exit;
add_action('template_redirect',static function(){if(is_admin()||wp_doing_ajax())return;$path=trim((string)wp_parse_url(isset($_SERVER['REQUEST_URI'])?wp_unslash($_SERVER['REQUEST_URI']):'',PHP_URL_PATH),'/');if(!preg_match('#^hub4?(?:/|$)#',$path))return;ob_start(static function($html){if(false===strpos($html,'class="mvm-hub4"')&&false===strpos($html,"class='mvm-hub4'"))return $html;if(false!==strpos($html,'id="mvm-hub-ai-agenda-ui-v1"'))return $html;$asset=<<<'MVMAG'
<script id="mvm-hub-ai-agenda-ui-v1">
(()=>{'use strict';const cfg=window.MvMHub4Config||{};if(!cfg.restRoot||!cfg.restNonce)return;let settings=null,loading=false;const api=async(path,options={})=>{const r=await fetch(new URL(String(path).replace(/^\//,''),cfg.restRoot).toString(),{...options,credentials:'same-origin',cache:'no-store',headers:{'X-WP-Nonce':cfg.restNonce,'Content-Type':'application/json','Accept':'application/json',...(options.headers||{})}});let j={};try{j=await r.json();}catch(e){}if(!r.ok)throw new Error(j.message||'Actie mislukt.');return j;};const el=(t,a={},text='')=>{const n=document.createElement(t);Object.entries(a).forEach(([k,v])=>{if(k==='class')n.className=v;else n.setAttribute(k,String(v));});if(text)n.textContent=text;return n;};
const load=async()=>{if(settings||loading)return settings;loading=true;try{settings=await api('agenda-crawl/settings');}catch(e){settings={denied:true};}loading=false;return settings;};
const sourceControl=async()=>{const section=[...document.querySelectorAll('.mvm-hub4__section')].find(s=>s.querySelector('h2')?.textContent.includes('Handmatige bronnencontrole'));if(!section||section.querySelector('[data-mvm-agenda-control]'))return;const s=await load();if(!s||s.denied)return;const box=el('div',{class:'mvm-agenda-crawl-control','data-mvm-agenda-control':'1'}),copy=el('div'),title=el('strong',{},'AI-agendacrawl');copy.appendChild(title);copy.appendChild(el('small',{},'Zoekt agenda/evenement-items bij actieve bronnen en zet nieuwe kandidaten in de bestaande Nieuwsradar AI-wachtrij.'));const controls=el('div',{class:'mvm-agenda-crawl-actions'}),label=el('label',{class:'mvm-agenda-switch'}),check=el('input',{type:'checkbox'}),state=el('span',{},s.enabled?'AAN':'UIT');check.checked=Boolean(s.enabled);label.append(check,state);const run=el('button',{type:'button'},'Nu controleren');run.disabled=!check.checked;const status=el('small',{class:'mvm-agenda-status'},s.lastMessage||'');controls.append(label,run);box.append(copy,controls,status);const head=section.querySelector('.mvm-hub4__section-head');(head?.parentNode||section).insertBefore(box,head?.nextSibling||section.firstChild);check.onchange=async()=>{check.disabled=true;try{settings=await api('agenda-crawl/settings',{method:'POST',body:JSON.stringify({enabled:check.checked})});state.textContent=check.checked?'AAN':'UIT';run.disabled=!check.checked;status.textContent=check.checked?'AI-agendacrawl is ingeschakeld. Eerste automatische ronde volgt binnen enkele minuten.':'AI-agendacrawl is uitgeschakeld.';}catch(e){check.checked=!check.checked;alert(e.message);}check.disabled=false;};run.onclick=async()=>{run.disabled=true;status.textContent='Bronagenda’s controleren…';try{const r=await api('agenda-crawl/run',{method:'POST',body:'{}'});status.textContent=r.message||'Controle afgerond.';}catch(e){status.textContent=e.message;}run.disabled=!check.checked;};};
const radarSort=async()=>{const toolbar=document.querySelector('.mvm-news-radar__toolbar');if(!toolbar||toolbar.querySelector('[data-mvm-radar-sort]'))return;const s=await load();if(!s||s.denied)return;const wrap=el('label',{class:'mvm-radar-sort-control','data-mvm-radar-sort':'1'});wrap.appendChild(el('span',{},'Onderwerpen sorteren'));const select=el('select');[['recent','Meest recent gepubliceerd'],['relevance','Hoogste lokale relevantie'],['radar','Originele Radarvolgorde']].forEach(([v,t])=>{const o=el('option',{value:v},t);if((s.radarSort||'recent')===v)o.selected=true;select.appendChild(o);});wrap.appendChild(select);toolbar.appendChild(wrap);select.onchange=async()=>{select.disabled=true;try{settings=await api('agenda-crawl/settings',{method:'POST',body:JSON.stringify({radarSort:select.value})});document.querySelector('[data-mvm-news-radar-view]')?.click();}catch(e){alert(e.message);}select.disabled=false;};};
const decorate=()=>{sourceControl();radarSort();};new MutationObserver(decorate).observe(document.documentElement,{childList:true,subtree:true});setInterval(decorate,900);})();
</script>
<style id="mvm-hub-ai-agenda-ui-v1-css">.mvm-agenda-crawl-control{display:grid;grid-template-columns:1fr auto;gap:10px 18px;align-items:center;margin:0 0 16px;padding:14px;border:1px solid var(--mvm-hub4-border,#c5d3df);border-radius:12px;background:var(--mvm-hub4-soft,#f6f9fc);color:var(--mvm-hub4-text,#17222d)}.mvm-agenda-crawl-control strong,.mvm-agenda-crawl-control small{display:block}.mvm-agenda-crawl-control small{margin-top:3px;color:var(--mvm-hub4-muted,#46596b)}.mvm-agenda-crawl-actions{display:flex;align-items:center;gap:8px}.mvm-agenda-switch{display:inline-flex!important;align-items:center;gap:7px;font-weight:800}.mvm-agenda-switch input{width:18px!important;height:18px!important}.mvm-agenda-crawl-actions button{min-height:36px;padding:7px 10px;border:1px solid #1966AE;border-radius:8px;background:#1966AE;color:#fff!important;font-weight:800}.mvm-agenda-status{grid-column:1/-1}.mvm-radar-sort-control{display:grid;gap:4px;min-width:220px}.mvm-radar-sort-control span{font-size:.78rem;font-weight:800}.mvm-radar-sort-control select{min-height:38px;padding:6px 8px;border:1px solid var(--mvm-hub4-border,#c5d3df);border-radius:8px;background:var(--mvm-hub4-surface,#fff);color:var(--mvm-hub4-text,#17222d)}@media(max-width:700px){.mvm-agenda-crawl-control{grid-template-columns:1fr}.mvm-agenda-crawl-actions{flex-wrap:wrap}.mvm-radar-sort-control{width:100%}}</style>
MVMAG;$p=stripos($html,'</head>');return false!==$p?substr_replace($html,$asset.'</head>',$p,7):$asset.$html;});},-840);